name: 'CI'

permissions:
    id-token: write # required for requesting the JWT
    contents: read  # required for actions/checkout

on:
  pull_request:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      dist:
        required: true
        description: Distribution type
        default: dev

jobs:
  lambdas-dist:
    environment: default
    name: AWS lambdas code distribution
    runs-on: ubuntu-latest
    env:
      DIST: ${{ github.event_name == 'release' && 'release' || 'dev' }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache-dependency-path: lambdas/go.mod

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3.x
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          # the identity provider for GH actions was created on AWS side to 
          # support assuming role while running the workflow
          # https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Run create_and_upload_bin
        if: github.event_name != 'workflow_dispatch'
        run: task create_and_upload_zip DIST=$DIST
     
      - name: Run create_and_upload_bin (workflow_dispatch)
        if: github.event_name == 'workflow_dispatch'
        run: task create_and_upload_zip DIST=${{ inputs.dist }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update lambdas_version'
          file_pattern: 'variables.tf'
